


// Default Region View Area
const LATITUDE_DELTA = 0.0922;
const LONGITUDE_DELTA = 0.0421;

// Default Marker View Area
const MARKER_LATITUDE_DELTA = 0.0222;
const MARKER_LONGITUDE_DELTA = 0.0121;

//  Polyline props
const POLYLINE_COLOR = "#1C32FA";
const POLYLINE_WIDTH = 4;

// Trap Point Marker props
const TRAP_POINT_MARKER_SIZE = 15;
const TRAP_POINT_MARKER_COLOR = "#00C220";


export {
  LATITUDE_DELTA,
  LONGITUDE_DELTA,
  MARKER_LATITUDE_DELTA,
  MARKER_LONGITUDE_DELTA,
  POLYLINE_COLOR,
  POLYLINE_WIDTH,
  TRAP_POINT_MARKER_SIZE,
  TRAP_POINT_MARKER_COLOR,
}